### ISSUE TITLE
Cool repo, thank you  

### ISSUE THREAD

**Issue by xiejiangzhi** [siara-cc/ruby_webview#1]
I'm trying to write a desktop app using Ruby, but not found a good way by webview.
Your project gave me some help.

It would be great if we could use it more easily. such as build a ruby gem and support more api of zserge/webview.

**Comment by siara-cc** [comment]
Thank you.  I will check whether it can be added as a gem and also look into expanding the API.

**Comment by xiejiangzhi** [comment]
@siara-cc  We can check the system type by RUBY_PLATFORM
https://stackoverflow.com/questions/170956/how-can-i-find-which-operating-system-my-ruby-program-is-running-on

Then, only one extconf.rb

**Comment by xiejiangzhi** [comment]
I found that maybe build a binary and support some RPC is easy.
then WebView access ruby server by http & websocket.

**Comment by siara-cc** [comment]
> Then, only one extconf.rb

When I was building, I checked it was possible, but lot of effort and complicated code.  Since everything anyway manual, I simply created separate extconf.rb.

**Comment by siara-cc** [comment]
> I found that maybe build a binary and support some RPC is easy.
> then WebView access ruby server by http & websocket.

It is already possible to access ruby server using WebView.  The difficulty is in creating installer for a fresh system that has no ruby.

**Comment by xiejiangzhi** [comment]
Yes, I didn't found a repo to do it for new ruby, but some repo already Implemented it for old ruby version.
Such as [pmq20/ruby-packer](/pmq20/ruby-packer).  Just build ruby for different platform.
In fact, I'll do it soon. My app is almost finished.

**Comment by xiejiangzhi** [comment]
Do you have a good way or tools to do it?
I want to build latest ruby(2.6.2), I didn't found ready binary package.

**Comment by siara-cc** [comment]
No.. I only know about the `ruby-packer` now.  Thanks for the info.  I don't have much experience with ruby.  I made this repo for a project.

**Comment by xiejiangzhi** [comment]
http://phusion.github.io/traveling-ruby/
https://github.com/stephan-nordnes-eriksen/ruby_ship

I just know those repos, but didn't try them yet.

**Comment by siara-cc** [comment]
I think you have lots of experience with Ruby

**Comment by xiejiangzhi** [comment]
Yes, but I didn't try to build ruby...
So your project makes me learn a new way. Although these things are all I know, I feel too much trouble, so I have never used them.

**Comment by xiejiangzhi** [comment]
https://github.com/xiejiangzhi/traveling-ruby

I successfully build the ruby 2.6.3 for OSX and linux. Because I am not familiar with configure&make, it took three or four days.

`ruby-packer` maybe better, but the repo is too large and hard to debug & change. So, I chosen `traveling-ruby`

**Comment by siara-cc** [comment]
Excellent..

**Comment by xiejiangzhi** [comment]
I have made a gem for this, hahaha

https://github.com/xiejiangzhi/webview

I tried build binary by golang, its code so easy.
